/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface TypesUpdateMenuReq
 */
export interface TypesUpdateMenuReq {
  /**
   * 菜单图标
   * @type {string}
   * @memberof TypesUpdateMenuReq
   */
  icon: string
  /**
   * 编号
   * @type {number}
   * @memberof TypesUpdateMenuReq
   */
  id: number
  /**
   * 菜单名称
   * @type {string}
   * @memberof TypesUpdateMenuReq
   */
  name: string
  /**
   * 排序
   * @type {number}
   * @memberof TypesUpdateMenuReq
   */
  orderNum: number
  /**
   * 父菜单ID，一级菜单为0
   * @type {number}
   * @memberof TypesUpdateMenuReq
   */
  parentId: number
  /**
   * 菜单URL,类型：1.普通页面（如用户管理， /sysmodel/user） 2.嵌套完整外部页面，以http(s)开头的链接 3.嵌套服务器页面，使用iframe:前缀+目标URL(如SQL监控， iframe:/druid/login.html, iframe:前缀会替换成服务器地址)
   * @type {string}
   * @memberof TypesUpdateMenuReq
   */
  path: string
  /**
   * 授权(多个用逗号分隔，如：sysmodel:user:add,sysmodel:user:edit)
   * @type {string}
   * @memberof TypesUpdateMenuReq
   */
  perms: string
  /**
   *
   * @type {number}
   * @memberof TypesUpdateMenuReq
   */
  status: number
  /**
   * 类型   0：目录   1：菜单   2：按钮
   * @type {number}
   * @memberof TypesUpdateMenuReq
   */
  type: number
}

/**
 * Check if a given object implements the TypesUpdateMenuReq interface.
 */
export function instanceOfTypesUpdateMenuReq(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && 'icon' in value
  isInstance = isInstance && 'id' in value
  isInstance = isInstance && 'name' in value
  isInstance = isInstance && 'orderNum' in value
  isInstance = isInstance && 'parentId' in value
  isInstance = isInstance && 'path' in value
  isInstance = isInstance && 'perms' in value
  isInstance = isInstance && 'status' in value
  isInstance = isInstance && 'type' in value

  return isInstance
}

export function TypesUpdateMenuReqFromJSON(json: any): TypesUpdateMenuReq {
  return TypesUpdateMenuReqFromJSONTyped(json, false)
}

export function TypesUpdateMenuReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesUpdateMenuReq {
  if (json === undefined || json === null) {
    return json
  }
  return {
    icon: json['icon'],
    id: json['id'],
    name: json['name'],
    orderNum: json['orderNum'],
    parentId: json['parentId'],
    path: json['path'],
    perms: json['perms'],
    status: json['status'],
    type: json['type'],
  }
}

export function TypesUpdateMenuReqToJSON(value?: TypesUpdateMenuReq | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    icon: value.icon,
    id: value.id,
    name: value.name,
    orderNum: value.orderNum,
    parentId: value.parentId,
    path: value.path,
    perms: value.perms,
    status: value.status,
    type: value.type,
  }
}
