/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface TypesAddUserReq
 */
export interface TypesAddUserReq {
  /**
   *
   * @type {string}
   * @memberof TypesAddUserReq
   */
  email: string
  /**
   *
   * @type {string}
   * @memberof TypesAddUserReq
   */
  mobile: string
  /**
   *
   * @type {string}
   * @memberof TypesAddUserReq
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof TypesAddUserReq
   */
  nickName: string
}

/**
 * Check if a given object implements the TypesAddUserReq interface.
 */
export function instanceOfTypesAddUserReq(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && 'email' in value
  isInstance = isInstance && 'mobile' in value
  isInstance = isInstance && 'name' in value
  isInstance = isInstance && 'nickName' in value

  return isInstance
}

export function TypesAddUserReqFromJSON(json: any): TypesAddUserReq {
  return TypesAddUserReqFromJSONTyped(json, false)
}

export function TypesAddUserReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesAddUserReq {
  if (json === undefined || json === null) {
    return json
  }
  return {
    email: json['email'],
    mobile: json['mobile'],
    name: json['name'],
    nickName: json['nickName'],
  }
}

export function TypesAddUserReqToJSON(value?: TypesAddUserReq | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    email: value.email,
    mobile: value.mobile,
    name: value.name,
    nickName: value.nickName,
  }
}
