/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface TypesAddMenuResp
 */
export interface TypesAddMenuResp {
  /**
   *
   * @type {string}
   * @memberof TypesAddMenuResp
   */
  code: string
  /**
   *
   * @type {string}
   * @memberof TypesAddMenuResp
   */
  message: string
}

/**
 * Check if a given object implements the TypesAddMenuResp interface.
 */
export function instanceOfTypesAddMenuResp(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && 'code' in value
  isInstance = isInstance && 'message' in value

  return isInstance
}

export function TypesAddMenuRespFromJSON(json: any): TypesAddMenuResp {
  return TypesAddMenuRespFromJSONTyped(json, false)
}

export function TypesAddMenuRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesAddMenuResp {
  if (json === undefined || json === null) {
    return json
  }
  return {
    code: json['code'],
    message: json['message'],
  }
}

export function TypesAddMenuRespToJSON(value?: TypesAddMenuResp | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    code: value.code,
    message: value.message,
  }
}
