/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface TypesUpdateRoleReq
 */
export interface TypesUpdateRoleReq {
  /**
   * 编号
   * @type {number}
   * @memberof TypesUpdateRoleReq
   */
  id: number
  /**
   * 角色名称
   * @type {string}
   * @memberof TypesUpdateRoleReq
   */
  name: string
  /**
   * 备注
   * @type {string}
   * @memberof TypesUpdateRoleReq
   */
  remark: string
  /**
   * 状态
   * @type {number}
   * @memberof TypesUpdateRoleReq
   */
  status: number
}

/**
 * Check if a given object implements the TypesUpdateRoleReq interface.
 */
export function instanceOfTypesUpdateRoleReq(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && 'id' in value
  isInstance = isInstance && 'name' in value
  isInstance = isInstance && 'remark' in value
  isInstance = isInstance && 'status' in value

  return isInstance
}

export function TypesUpdateRoleReqFromJSON(json: any): TypesUpdateRoleReq {
  return TypesUpdateRoleReqFromJSONTyped(json, false)
}

export function TypesUpdateRoleReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesUpdateRoleReq {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
    name: json['name'],
    remark: json['remark'],
    status: json['status'],
  }
}

export function TypesUpdateRoleReqToJSON(value?: TypesUpdateRoleReq | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    name: value.name,
    remark: value.remark,
    status: value.status,
  }
}
