/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface TypesUserInfoResp
 */
export interface TypesUserInfoResp {
  /**
   *
   * @type {string}
   * @memberof TypesUserInfoResp
   */
  avatar: string
  /**
   *
   * @type {string}
   * @memberof TypesUserInfoResp
   */
  name: string
}

/**
 * Check if a given object implements the TypesUserInfoResp interface.
 */
export function instanceOfTypesUserInfoResp(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && 'avatar' in value
  isInstance = isInstance && 'name' in value

  return isInstance
}

export function TypesUserInfoRespFromJSON(json: any): TypesUserInfoResp {
  return TypesUserInfoRespFromJSONTyped(json, false)
}

export function TypesUserInfoRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesUserInfoResp {
  if (json === undefined || json === null) {
    return json
  }
  return {
    avatar: json['avatar'],
    name: json['name'],
  }
}

export function TypesUserInfoRespToJSON(value?: TypesUserInfoResp | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    avatar: value.avatar,
    name: value.name,
  }
}
