/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { TypesListMenuData } from './TypesListMenuData'
import { TypesListMenuDataFromJSON, TypesListMenuDataFromJSONTyped, TypesListMenuDataToJSON } from './TypesListMenuData'

/**
 *
 * @export
 * @interface TypesListMenuResp
 */
export interface TypesListMenuResp {
  /**
   *
   * @type {string}
   * @memberof TypesListMenuResp
   */
  code: string
  /**
   *
   * @type {Array<TypesListMenuData>}
   * @memberof TypesListMenuResp
   */
  data: Array<TypesListMenuData>
  /**
   *
   * @type {string}
   * @memberof TypesListMenuResp
   */
  message: string
  /**
   *
   * @type {boolean}
   * @memberof TypesListMenuResp
   */
  success: boolean
  /**
   *
   * @type {number}
   * @memberof TypesListMenuResp
   */
  total: number
}

/**
 * Check if a given object implements the TypesListMenuResp interface.
 */
export function instanceOfTypesListMenuResp(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && 'code' in value
  isInstance = isInstance && 'data' in value
  isInstance = isInstance && 'message' in value
  isInstance = isInstance && 'success' in value
  isInstance = isInstance && 'total' in value

  return isInstance
}

export function TypesListMenuRespFromJSON(json: any): TypesListMenuResp {
  return TypesListMenuRespFromJSONTyped(json, false)
}

export function TypesListMenuRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesListMenuResp {
  if (json === undefined || json === null) {
    return json
  }
  return {
    code: json['code'],
    data: (json['data'] as Array<any>).map(TypesListMenuDataFromJSON),
    message: json['message'],
    success: json['success'],
    total: json['total'],
  }
}

export function TypesListMenuRespToJSON(value?: TypesListMenuResp | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    code: value.code,
    data: (value.data as Array<any>).map(TypesListMenuDataToJSON),
    message: value.message,
    success: value.success,
    total: value.total,
  }
}
