/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface TypesAddMenuReq
 */
export interface TypesAddMenuReq {
  /**
   * 菜单图标
   * @type {string}
   * @memberof TypesAddMenuReq
   */
  icon: string
  /**
   * 菜单名称
   * @type {string}
   * @memberof TypesAddMenuReq
   */
  name: string
  /**
   * 排序
   * @type {number}
   * @memberof TypesAddMenuReq
   */
  orderNum: number
  /**
   * 父菜单ID，一级菜单为0
   * @type {number}
   * @memberof TypesAddMenuReq
   */
  parentId: number
  /**
   * 菜单URL,类型：1.普通页面（如用户管理， /sysmodel/user） 2.嵌套完整外部页面，以http(s)开头的链接 3.嵌套服务器页面，使用iframe:前缀+目标URL(如SQL监控， iframe:/druid/login.html, iframe:前缀会替换成服务器地址)
   * @type {string}
   * @memberof TypesAddMenuReq
   */
  path: string
  /**
   * 授权(多个用逗号分隔，如：sysmodel:user:add,sysmodel:user:edit)
   * @type {string}
   * @memberof TypesAddMenuReq
   */
  perms: string
  /**
   * 类型   0：目录   1：菜单   2：按钮
   * @type {number}
   * @memberof TypesAddMenuReq
   */
  type: number
}

/**
 * Check if a given object implements the TypesAddMenuReq interface.
 */
export function instanceOfTypesAddMenuReq(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && 'icon' in value
  isInstance = isInstance && 'name' in value
  isInstance = isInstance && 'orderNum' in value
  isInstance = isInstance && 'parentId' in value
  isInstance = isInstance && 'path' in value
  isInstance = isInstance && 'perms' in value
  isInstance = isInstance && 'type' in value

  return isInstance
}

export function TypesAddMenuReqFromJSON(json: any): TypesAddMenuReq {
  return TypesAddMenuReqFromJSONTyped(json, false)
}

export function TypesAddMenuReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesAddMenuReq {
  if (json === undefined || json === null) {
    return json
  }
  return {
    icon: json['icon'],
    name: json['name'],
    orderNum: json['orderNum'],
    parentId: json['parentId'],
    path: json['path'],
    perms: json['perms'],
    type: json['type'],
  }
}

export function TypesAddMenuReqToJSON(value?: TypesAddMenuReq | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    icon: value.icon,
    name: value.name,
    orderNum: value.orderNum,
    parentId: value.parentId,
    path: value.path,
    perms: value.perms,
    type: value.type,
  }
}
