/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface TypesUserLoginReq
 */
export interface TypesUserLoginReq {
  /**
   *
   * @type {string}
   * @memberof TypesUserLoginReq
   */
  password: string
  /**
   *
   * @type {string}
   * @memberof TypesUserLoginReq
   */
  userName: string
}

/**
 * Check if a given object implements the TypesUserLoginReq interface.
 */
export function instanceOfTypesUserLoginReq(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && 'password' in value
  isInstance = isInstance && 'userName' in value

  return isInstance
}

export function TypesUserLoginReqFromJSON(json: any): TypesUserLoginReq {
  return TypesUserLoginReqFromJSONTyped(json, false)
}

export function TypesUserLoginReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesUserLoginReq {
  if (json === undefined || json === null) {
    return json
  }
  return {
    password: json['password'],
    userName: json['userName'],
  }
}

export function TypesUserLoginReqToJSON(value?: TypesUserLoginReq | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    password: value.password,
    userName: value.userName,
  }
}
