/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface TypesUpdateUserResp
 */
export interface TypesUpdateUserResp {
  /**
   *
   * @type {string}
   * @memberof TypesUpdateUserResp
   */
  code: string
  /**
   *
   * @type {string}
   * @memberof TypesUpdateUserResp
   */
  message: string
}

/**
 * Check if a given object implements the TypesUpdateUserResp interface.
 */
export function instanceOfTypesUpdateUserResp(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && 'code' in value
  isInstance = isInstance && 'message' in value

  return isInstance
}

export function TypesUpdateUserRespFromJSON(json: any): TypesUpdateUserResp {
  return TypesUpdateUserRespFromJSONTyped(json, false)
}

export function TypesUpdateUserRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesUpdateUserResp {
  if (json === undefined || json === null) {
    return json
  }
  return {
    code: json['code'],
    message: json['message'],
  }
}

export function TypesUpdateUserRespToJSON(value?: TypesUpdateUserResp | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    code: value.code,
    message: value.message,
  }
}
