/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {
  TypesAddMenuReq,
  TypesAddMenuResp,
  TypesAddRoleReq,
  TypesAddRoleResp,
  TypesAddUserReq,
  TypesAddUserResp,
  TypesDeleteMenuReq,
  TypesDeleteMenuResp,
  TypesDeleteRoleReq,
  TypesDeleteRoleResp,
  TypesDeleteUserReq,
  TypesDeleteUserResp,
  TypesListMenuResp,
  TypesListRoleResp,
  TypesListUserResp,
  TypesUpdateMenuReq,
  TypesUpdateMenuResp,
  TypesUpdateRoleReq,
  TypesUpdateRoleResp,
  TypesUpdateUserReq,
  TypesUpdateUserResp,
  TypesUserInfoResp,
  TypesUserLoginReq,
  TypesUserLoginResp,
} from '../models'
import {
  TypesAddMenuReqFromJSON,
  TypesAddMenuReqToJSON,
  TypesAddMenuRespFromJSON,
  TypesAddMenuRespToJSON,
  TypesAddRoleReqFromJSON,
  TypesAddRoleReqToJSON,
  TypesAddRoleRespFromJSON,
  TypesAddRoleRespToJSON,
  TypesAddUserReqFromJSON,
  TypesAddUserReqToJSON,
  TypesAddUserRespFromJSON,
  TypesAddUserRespToJSON,
  TypesDeleteMenuReqFromJSON,
  TypesDeleteMenuReqToJSON,
  TypesDeleteMenuRespFromJSON,
  TypesDeleteMenuRespToJSON,
  TypesDeleteRoleReqFromJSON,
  TypesDeleteRoleReqToJSON,
  TypesDeleteRoleRespFromJSON,
  TypesDeleteRoleRespToJSON,
  TypesDeleteUserReqFromJSON,
  TypesDeleteUserReqToJSON,
  TypesDeleteUserRespFromJSON,
  TypesDeleteUserRespToJSON,
  TypesListMenuRespFromJSON,
  TypesListMenuRespToJSON,
  TypesListRoleRespFromJSON,
  TypesListRoleRespToJSON,
  TypesListUserRespFromJSON,
  TypesListUserRespToJSON,
  TypesUpdateMenuReqFromJSON,
  TypesUpdateMenuReqToJSON,
  TypesUpdateMenuRespFromJSON,
  TypesUpdateMenuRespToJSON,
  TypesUpdateRoleReqFromJSON,
  TypesUpdateRoleReqToJSON,
  TypesUpdateRoleRespFromJSON,
  TypesUpdateRoleRespToJSON,
  TypesUpdateUserReqFromJSON,
  TypesUpdateUserReqToJSON,
  TypesUpdateUserRespFromJSON,
  TypesUpdateUserRespToJSON,
  TypesUserInfoRespFromJSON,
  TypesUserInfoRespToJSON,
  TypesUserLoginReqFromJSON,
  TypesUserLoginReqToJSON,
  TypesUserLoginRespFromJSON,
  TypesUserLoginRespToJSON,
} from '../models'

export interface MenuAddRequest {
  body: TypesAddMenuReq
}

export interface MenuDeleteRequest {
  body: TypesDeleteMenuReq
}

export interface MenuListRequest {
  name?: string
  path?: string
  status?: number
}

export interface MenuUpdateRequest {
  body: TypesUpdateMenuReq
}

export interface RoleAddRequest {
  body: TypesAddRoleReq
}

export interface RoleDeleteRequest {
  body: TypesDeleteRoleReq
}

export interface RoleListRequest {
  name?: string
  status?: number
}

export interface RoleUpdateRequest {
  body: TypesUpdateRoleReq
}

export interface UserAddRequest {
  body: TypesAddUserReq
}

export interface UserDeleteRequest {
  body: TypesDeleteUserReq
}

export interface UserInfoRequest {
  userId: string
}

export interface UserListRequest {
  current?: number
  pageSize?: number
  name?: string
  nickName?: string
  mobile?: string
  email?: string
  status?: number
}

export interface UserLoginRequest {
  userLogin: TypesUserLoginReq
}

export interface UserUpdateRequest {
  body: TypesUpdateUserReq
}

/**
 * PureApi - interface
 *
 * @export
 * @interface PureApiInterface
 */
export interface PureApiInterface {
  /**
   * menu add
   * @summary menu add logic
   * @param {TypesAddMenuReq} body menu add
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PureApiInterface
   */
  menuAddRaw(
    requestParameters: MenuAddRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesAddMenuResp>>

  /**
   * menu add
   * menu add logic
   */
  menuAdd(
    requestParameters: MenuAddRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesAddMenuResp>

  /**
   * menu delete
   * @summary menu delete logic
   * @param {TypesDeleteMenuReq} body menu delete
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PureApiInterface
   */
  menuDeleteRaw(
    requestParameters: MenuDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesDeleteMenuResp>>

  /**
   * menu delete
   * menu delete logic
   */
  menuDelete(
    requestParameters: MenuDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesDeleteMenuResp>

  /**
   * menu list
   * @summary menu list logic
   * @param {string} [name] List Menu
   * @param {string} [path] List Menu
   * @param {number} [status] List Menu
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PureApiInterface
   */
  menuListRaw(
    requestParameters: MenuListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesListMenuResp>>

  /**
   * menu list
   * menu list logic
   */
  menuList(
    requestParameters: MenuListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesListMenuResp>

  /**
   * menu update
   * @summary menu update logic
   * @param {TypesUpdateMenuReq} body menu update
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PureApiInterface
   */
  menuUpdateRaw(
    requestParameters: MenuUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesUpdateMenuResp>>

  /**
   * menu update
   * menu update logic
   */
  menuUpdate(
    requestParameters: MenuUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesUpdateMenuResp>

  /**
   * role add
   * @summary role add logic
   * @param {TypesAddRoleReq} body role add
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PureApiInterface
   */
  roleAddRaw(
    requestParameters: RoleAddRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesAddRoleResp>>

  /**
   * role add
   * role add logic
   */
  roleAdd(
    requestParameters: RoleAddRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesAddRoleResp>

  /**
   * role delete
   * @summary role delete logic
   * @param {TypesDeleteRoleReq} body role delete
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PureApiInterface
   */
  roleDeleteRaw(
    requestParameters: RoleDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesDeleteRoleResp>>

  /**
   * role delete
   * role delete logic
   */
  roleDelete(
    requestParameters: RoleDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesDeleteRoleResp>

  /**
   * role list
   * @summary role list logic
   * @param {string} [name] list role
   * @param {number} [status] list role
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PureApiInterface
   */
  roleListRaw(
    requestParameters: RoleListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesListRoleResp>>

  /**
   * role list
   * role list logic
   */
  roleList(
    requestParameters: RoleListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesListRoleResp>

  /**
   * role update
   * @summary role update logic
   * @param {TypesUpdateRoleReq} body role update
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PureApiInterface
   */
  roleUpdateRaw(
    requestParameters: RoleUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesUpdateRoleResp>>

  /**
   * role update
   * role update logic
   */
  roleUpdate(
    requestParameters: RoleUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesUpdateRoleResp>

  /**
   * user add
   * @summary user add logic
   * @param {TypesAddUserReq} body user add
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PureApiInterface
   */
  userAddRaw(
    requestParameters: UserAddRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesAddUserResp>>

  /**
   * user add
   * user add logic
   */
  userAdd(
    requestParameters: UserAddRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesAddUserResp>

  /**
   * user delete
   * @summary user delete logic
   * @param {TypesDeleteUserReq} body user delete
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PureApiInterface
   */
  userDeleteRaw(
    requestParameters: UserDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesDeleteUserResp>>

  /**
   * user delete
   * user delete logic
   */
  userDelete(
    requestParameters: UserDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesDeleteUserResp>

  /**
   * user info
   * @summary user info logic
   * @param {string} userId userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PureApiInterface
   */
  userInfoRaw(
    requestParameters: UserInfoRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesUserInfoResp>>

  /**
   * user info
   * user info logic
   */
  userInfo(
    requestParameters: UserInfoRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesUserInfoResp>

  /**
   * user list
   * @summary user list logic
   * @param {number} [current] List User
   * @param {number} [pageSize] List User
   * @param {string} [name] List User
   * @param {string} [nickName] List User
   * @param {string} [mobile] List User
   * @param {string} [email] List User
   * @param {number} [status] List User
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PureApiInterface
   */
  userListRaw(
    requestParameters: UserListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesListUserResp>>

  /**
   * user list
   * user list logic
   */
  userList(
    requestParameters: UserListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesListUserResp>

  /**
   * user login
   * @summary user login logic
   * @param {TypesUserLoginReq} userLogin Login info
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PureApiInterface
   */
  userLoginRaw(
    requestParameters: UserLoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesUserLoginResp>>

  /**
   * user login
   * user login logic
   */
  userLogin(
    requestParameters: UserLoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesUserLoginResp>

  /**
   * user update
   * @summary user update logic
   * @param {TypesUpdateUserReq} body user update
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PureApiInterface
   */
  userUpdateRaw(
    requestParameters: UserUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesUpdateUserResp>>

  /**
   * user update
   * user update logic
   */
  userUpdate(
    requestParameters: UserUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesUpdateUserResp>
}

/**
 *
 */
export class PureApi extends runtime.BaseAPI implements PureApiInterface {
  /**
   * menu add
   * menu add logic
   */
  async menuAddRaw(
    requestParameters: MenuAddRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesAddMenuResp>> {
    if (requestParameters.body === null || requestParameters.body === undefined) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling menuAdd.',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/api/sys/menu/add`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: TypesAddMenuReqToJSON(requestParameters.body),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => TypesAddMenuRespFromJSON(jsonValue))
  }

  /**
   * menu add
   * menu add logic
   */
  async menuAdd(
    requestParameters: MenuAddRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesAddMenuResp> {
    const response = await this.menuAddRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * menu delete
   * menu delete logic
   */
  async menuDeleteRaw(
    requestParameters: MenuDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesDeleteMenuResp>> {
    if (requestParameters.body === null || requestParameters.body === undefined) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling menuDelete.',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/api/sys/menu/delete`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: TypesDeleteMenuReqToJSON(requestParameters.body),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => TypesDeleteMenuRespFromJSON(jsonValue))
  }

  /**
   * menu delete
   * menu delete logic
   */
  async menuDelete(
    requestParameters: MenuDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesDeleteMenuResp> {
    const response = await this.menuDeleteRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * menu list
   * menu list logic
   */
  async menuListRaw(
    requestParameters: MenuListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesListMenuResp>> {
    const queryParameters: any = {}

    if (requestParameters.name !== undefined) {
      queryParameters['name'] = requestParameters.name
    }

    if (requestParameters.path !== undefined) {
      queryParameters['path'] = requestParameters.path
    }

    if (requestParameters.status !== undefined) {
      queryParameters['status'] = requestParameters.status
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = this.configuration.apiKey('Authorization') // ApiKeyAuth authentication
    }

    const response = await this.request(
      {
        path: `/api/sys/menu/list`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => TypesListMenuRespFromJSON(jsonValue))
  }

  /**
   * menu list
   * menu list logic
   */
  async menuList(
    requestParameters: MenuListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesListMenuResp> {
    const response = await this.menuListRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * menu update
   * menu update logic
   */
  async menuUpdateRaw(
    requestParameters: MenuUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesUpdateMenuResp>> {
    if (requestParameters.body === null || requestParameters.body === undefined) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling menuUpdate.',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/api/sys/menu/update`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: TypesUpdateMenuReqToJSON(requestParameters.body),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => TypesUpdateMenuRespFromJSON(jsonValue))
  }

  /**
   * menu update
   * menu update logic
   */
  async menuUpdate(
    requestParameters: MenuUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesUpdateMenuResp> {
    const response = await this.menuUpdateRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * role add
   * role add logic
   */
  async roleAddRaw(
    requestParameters: RoleAddRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesAddRoleResp>> {
    if (requestParameters.body === null || requestParameters.body === undefined) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling roleAdd.',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/api/sys/role/add`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: TypesAddRoleReqToJSON(requestParameters.body),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => TypesAddRoleRespFromJSON(jsonValue))
  }

  /**
   * role add
   * role add logic
   */
  async roleAdd(
    requestParameters: RoleAddRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesAddRoleResp> {
    const response = await this.roleAddRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * role delete
   * role delete logic
   */
  async roleDeleteRaw(
    requestParameters: RoleDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesDeleteRoleResp>> {
    if (requestParameters.body === null || requestParameters.body === undefined) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling roleDelete.',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/api/sys/role/delete`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: TypesDeleteRoleReqToJSON(requestParameters.body),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => TypesDeleteRoleRespFromJSON(jsonValue))
  }

  /**
   * role delete
   * role delete logic
   */
  async roleDelete(
    requestParameters: RoleDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesDeleteRoleResp> {
    const response = await this.roleDeleteRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * role list
   * role list logic
   */
  async roleListRaw(
    requestParameters: RoleListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesListRoleResp>> {
    const queryParameters: any = {}

    if (requestParameters.name !== undefined) {
      queryParameters['name'] = requestParameters.name
    }

    if (requestParameters.status !== undefined) {
      queryParameters['status'] = requestParameters.status
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = this.configuration.apiKey('Authorization') // ApiKeyAuth authentication
    }

    const response = await this.request(
      {
        path: `/api/sys/role/list`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => TypesListRoleRespFromJSON(jsonValue))
  }

  /**
   * role list
   * role list logic
   */
  async roleList(
    requestParameters: RoleListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesListRoleResp> {
    const response = await this.roleListRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * role update
   * role update logic
   */
  async roleUpdateRaw(
    requestParameters: RoleUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesUpdateRoleResp>> {
    if (requestParameters.body === null || requestParameters.body === undefined) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling roleUpdate.',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/api/sys/role/update`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: TypesUpdateRoleReqToJSON(requestParameters.body),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => TypesUpdateRoleRespFromJSON(jsonValue))
  }

  /**
   * role update
   * role update logic
   */
  async roleUpdate(
    requestParameters: RoleUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesUpdateRoleResp> {
    const response = await this.roleUpdateRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * user add
   * user add logic
   */
  async userAddRaw(
    requestParameters: UserAddRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesAddUserResp>> {
    if (requestParameters.body === null || requestParameters.body === undefined) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling userAdd.',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/api/sys/user/add`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: TypesAddUserReqToJSON(requestParameters.body),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => TypesAddUserRespFromJSON(jsonValue))
  }

  /**
   * user add
   * user add logic
   */
  async userAdd(
    requestParameters: UserAddRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesAddUserResp> {
    const response = await this.userAddRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * user delete
   * user delete logic
   */
  async userDeleteRaw(
    requestParameters: UserDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesDeleteUserResp>> {
    if (requestParameters.body === null || requestParameters.body === undefined) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling userDelete.',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/api/sys/user/delete`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: TypesDeleteUserReqToJSON(requestParameters.body),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => TypesDeleteUserRespFromJSON(jsonValue))
  }

  /**
   * user delete
   * user delete logic
   */
  async userDelete(
    requestParameters: UserDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesDeleteUserResp> {
    const response = await this.userDeleteRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * user info
   * user info logic
   */
  async userInfoRaw(
    requestParameters: UserInfoRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesUserInfoResp>> {
    if (requestParameters.userId === null || requestParameters.userId === undefined) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter requestParameters.userId was null or undefined when calling userInfo.',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (requestParameters.userId !== undefined && requestParameters.userId !== null) {
      headerParameters['userId'] = String(requestParameters.userId)
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = this.configuration.apiKey('Authorization') // ApiKeyAuth authentication
    }

    const response = await this.request(
      {
        path: `/api/sys/user/currentUser`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => TypesUserInfoRespFromJSON(jsonValue))
  }

  /**
   * user info
   * user info logic
   */
  async userInfo(
    requestParameters: UserInfoRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesUserInfoResp> {
    const response = await this.userInfoRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * user list
   * user list logic
   */
  async userListRaw(
    requestParameters: UserListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesListUserResp>> {
    const queryParameters: any = {}

    if (requestParameters.current !== undefined) {
      queryParameters['current'] = requestParameters.current
    }

    if (requestParameters.pageSize !== undefined) {
      queryParameters['pageSize'] = requestParameters.pageSize
    }

    if (requestParameters.name !== undefined) {
      queryParameters['name'] = requestParameters.name
    }

    if (requestParameters.nickName !== undefined) {
      queryParameters['nickName'] = requestParameters.nickName
    }

    if (requestParameters.mobile !== undefined) {
      queryParameters['mobile'] = requestParameters.mobile
    }

    if (requestParameters.email !== undefined) {
      queryParameters['email'] = requestParameters.email
    }

    if (requestParameters.status !== undefined) {
      queryParameters['status'] = requestParameters.status
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = this.configuration.apiKey('Authorization') // ApiKeyAuth authentication
    }

    const response = await this.request(
      {
        path: `/api/sys/user/list`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => TypesListUserRespFromJSON(jsonValue))
  }

  /**
   * user list
   * user list logic
   */
  async userList(
    requestParameters: UserListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesListUserResp> {
    const response = await this.userListRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * user login
   * user login logic
   */
  async userLoginRaw(
    requestParameters: UserLoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesUserLoginResp>> {
    if (requestParameters.userLogin === null || requestParameters.userLogin === undefined) {
      throw new runtime.RequiredError(
        'userLogin',
        'Required parameter requestParameters.userLogin was null or undefined when calling userLogin.',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/api/sys/user/login`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: TypesUserLoginReqToJSON(requestParameters.userLogin),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => TypesUserLoginRespFromJSON(jsonValue))
  }

  /**
   * user login
   * user login logic
   */
  async userLogin(
    requestParameters: UserLoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesUserLoginResp> {
    const response = await this.userLoginRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * user update
   * user update logic
   */
  async userUpdateRaw(
    requestParameters: UserUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TypesUpdateUserResp>> {
    if (requestParameters.body === null || requestParameters.body === undefined) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling userUpdate.',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/api/sys/user/update`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: TypesUpdateUserReqToJSON(requestParameters.body),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => TypesUpdateUserRespFromJSON(jsonValue))
  }

  /**
   * user update
   * user update logic
   */
  async userUpdate(
    requestParameters: UserUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TypesUpdateUserResp> {
    const response = await this.userUpdateRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
